name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  Test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Container
        run: docker build -t drone-server:latest .
        
      - name: Start Containers
        run: docker-compose -f "drone.yaml" up -d
        
      - name: Install dependecies
        run: pip install pymongo
        
      - name: Run Tests
        run: python tests/tests.py
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "drone.yaml" down
        
  Build_and_Push:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: anastasofpv/drone-server:${{ github.run_number }}
